config-type: rule
id: github-org-advanced-security
name: Verify advanced security setting is enabled
path: advanced-security.rego

description: Verify `advanced_security_enabled_for_new_repositories` is enabled for new repositories in the GitHub organization.

labels:
  - GitHub
  - Organization

evidence:
  signed: false
  content_body_type: generic
  target_type: data
  predicate_type: http://scribesecurity.com/evidence/discovery/v0.1
  labels:
    - "platform=github"
    - "asset_type=organization"
    - >-
      {{- if eq (index .Context "asset-type") "organization" -}}
      {{- asset_on_target (index .Context "asset-name") -}}
      {{- else -}}
      {{- asset_on_target nil -}}
      {{- end -}}

with:
  desired_value: false
