config-type: rule
id: github-org-dependabot-security-updates
name: Verify dependabot_security_updates_enabled_for_new_repositories setting
path: dependabot-security-updates.rego

description: Verify Dependabot security updates for new repositories are configured in the GitHub organization.

full-description: |-
  This rule ensures that Dependabot security updates are enabled for new repositories in the GitHub organization.
  It performs the following steps:
  
  1. Checks the security and analysis settings of the GitHub organization.
  2. Verifies that the Dependabot security updates setting is enabled for new repositories.

  **Evidence Requirements:**
  - Evidence must be provided by the Scribe Platform's CLI tool through scanning GitHub organization resources.

mitigation: >-
  Ensures that Dependabot security updates are enabled for new repositories in the GitHub organization, reducing the risk of vulnerabilities in dependencies.

inputs:
  - name: desired_value
    type: boolean
    description: Indicates if Dependabot security updates for new repositories are enabled.
    required: false

input_example: |-
  desired_value: true

labels:
  - GitHub
  - Organization

evidence:
  filter-by:
    - product
    - target
  signed: false
  content_body_type: generic
  target_type: data
  predicate_type: http://scribesecurity.com/evidence/discovery/v0.1
  asset_platform: github
  asset_type: organization

with:
  desired_value: true

