config-type: rule
id: github-org-dependabot-security-updates-sa
name: "Dependabot security updates enabled for security and analysis"
path: dependabot-security-updates-sa.rego

description: "A rule to verify that dependabot_security_updates in security_and_analysis is properly set"

labels:
  - GitHub
  - Organization

evidence:
  signed: false
  content_body_type: generic
  target_type: data
  predicate_type: http://scribesecurity.com/evidence/discovery/v0.1
  labels:
    - "platform=github"
    - "asset_type=organization"
    
