config-type: rule
id: github-org-dependabot-security-updates
name: Verify dependabot_security_updates_enabled_for_new_repositories setting
path: dependabot-security-updates.rego

description: Verify Dependabot security updates for new repositories are configured in the GitHub organization.

labels:
  - GitHub
  - Organization

evidence:
  signed: false
  content_body_type: generic
  target_type: data
  predicate_type: http://scribesecurity.com/evidence/discovery/v0.1
  labels:
    - "platform=github"
    - "asset_type=organization"

with:
  desired_value: false
