config-type: rule
id: github-org-dependabot-security-updates-sa
name: Verify dependabot_security_updates setting in security_and_analysis
path: dependabot-security-updates-sa.rego

description: Verify Dependabot security updates are configured in the GitHub organization.

labels:
  - GitHub
  - Organization

evidence:
  signed: false
  content_body_type: generic
  target_type: data
  predicate_type: http://scribesecurity.com/evidence/discovery/v0.1
  labels:
    - "platform=github"
    - "asset_type=organization"
