name: advanced-security
path: advanced-security.rego

level: warning

description: "A rule to verify that the binary field: advanced_security_enabled_for_new_repositories is properly set"

evidence:
  signed: false
  content_body_type: generic
  target_type: data
  predicate_type: http://scribesecurity.com/evidence/discovery/v0.1
  labels:
    - "asset_type=organization"

with:
  desired_value: false
  
