config-type: rule
id: k8s-pods-verify-pod-termination
name: Verify Pod Termination
path: verify-pod-termination.rego

description: Verify Kubernetes pods are properly terminated to prevent lingering resources and maintain cluster hygiene.

labels:
  - K8s
  - Pod

evidence:
  signed: false
  content_body_type: generic
  target_type: data
  predicate_type: http://scribesecurity.com/evidence/discovery/v0.1
  labels:
    - "asset_type=pod"
