config-type: rule
id: k8s-pods-verify-pod-duration
name: Verify Pod Runtime Duration
path: verify-pod-duration.rego

description: Verify Kubernetes pods adhere to a specified runtime duration to enforce lifecycle limits.

full-description: |-
  This rule verifies that the duration of pods in Kubernetes does not exceed the specified limit.
  It performs the following steps:
  
  1. Iterates over the pods in the cluster.
  2. Checks each pod's duration against the limit specified in the `with.max_days` configuration.
     - If a pod's duration exceeds the limit, the rule flags it as a violation.

  **Evidence Requirements:**
  - Evidence must be provided by the Scribe Platform's CLI tool through scanning Kubernetes resources.

mitigation: >-
  Ensures that pods do not exceed their intended lifecycle, maintaining cluster hygiene and resource efficiency.

inputs:
  - name: max_days
    description: "The maximum allowed duration for pods in days."
    type: integer
    required: false

input_example: |-
  max_days: 30

labels:
  - K8s
  - Pod

evidence:
  filter-by:
    - product
    - target
  signed: false
  content_body_type: generic
  target_type: data
  predicate_type: http://scribesecurity.com/evidence/discovery/v0.1
  asset_platform: k8s
  asset_type: pod
    
with:
  max_days: 30
