config-type: rule
id: k8s-pods-verify-pod-duration
name: Verify Pod Runtime Duration
path: verify-pod-duration.rego

description: Verify Kubernetes pods adhere to a specified runtime duration to enforce lifecycle limits.

labels:
  - K8s
  - Pod

evidence:
  signed: false
  content_body_type: generic
  target_type: data
  predicate_type: http://scribesecurity.com/evidence/discovery/v0.1
  labels:
    - "asset_type=pod"

with:
  max_days: "30"
