config-type: rule
id: k8s-pods-white-listed-pod
name: Allowed Pods
path: white-listed-pod.rego

description: Verify only pods explicitly listed in the Allowed List are allowed to run.

labels:
  - K8s
  - Pod

evidence:
  signed: false
  content_body_type: generic
  target_type: data
  predicate_type: http://scribesecurity.com/evidence/discovery/v0.1
  labels:
    - "asset_type=pod"
    - "platform=k8s"

with:
  white_listed_pod: []
  verify_namespaces:
    - ".*"

inputs:
  - name: white_listed_pod
    description: "A list of allowed pods (supports regex)."
    type: array
    required: true
  - name: verify_namespaces
    description: "A list of namespaces to verify (supports regex)."
    type: array
    required: true

full-description: |
  This rule ensures that only pods specified in the whitelist are allowed to run within the Kubernetes cluster.
  It performs the following steps:
  
  1. Iterates over the pods in the cluster.
  2. Checks each pod against the whitelist specified in the `with.white_listed_pod` configuration.
     - If a pod is not in the whitelist, the rule flags it as a violation.

  **Evidence Requirements:**
  - Evidence must be provided by the Scribe Platform's CLI tool through scanning Kubernetes resources.

notes: |
  **Input Example:**
  
  ```yaml
  - uses: k8s/pods/white-listed-pod@v2/rules
    with:
      white_listed_pod:
        - my-pod-1.*
        - my-pod-2.*
      verify_namespaces:
        - ".*"
  ```

mitigation: >
  Ensures that only approved pods are running within the Kubernetes cluster, reducing the risk of unauthorized or misconfigured pods.
