config-type: rule
id: k8s-namespace-blocked-images
name: "K8s Namespace Blocked Images"
path: blocked-images.rego

description: "A rule to verify that all images are allowed"

labels:
  - K8s
  - Namespace

evidence:
  signed: false
  content_body_type: generic
  target_type: data
  predicate_type: http://scribesecurity.com/evidence/discovery/v0.1
  labels:
    - "asset_type=namespace"

with:
  images_to_include: []
