config-type: rule
id: k8s-namespace-allowed-registries
name: Allowed Namespace Registries
path: allowed-registries.rego

description: Verify container images in Kubernetes namespaces originate from registries in the Allowed List.

labels:
  - K8s
  - Namespace

evidence:
  signed: false
  content_body_type: generic
  target_type: data
  predicate_type: http://scribesecurity.com/evidence/discovery/v0.1
  labels:
    - "asset_type=namespace"

with:
    allowed_registries: []
