config-type: rule
id: k8s-namespace-exists
name: Require K8s Namespace Discovery Evidence
path: evidence-exists.rego

description: Verify the K8s Namespace exists as evidence.

labels:
  - K8s
  - Namespace

fail-on-missing-evidence: true

evidence:
  signed: false
  content_body_type: generic
  target_type: data
  predicate_type: http://scribesecurity.com/evidence/discovery/v0.1
  asset_platform: k8s
  asset_type: namespace
  asset_name: >-
              {{- if eq .Context.asset_type "namespace" -}}
              {{- on_target .Context.asset_name -}}
              {{- else -}}
              {{- on_target nil -}}
              {{- end -}}
