config-type: rule
id: k8s-namespace-exists
name: Require K8s Namespace Discovery Evidence
path: evidence-exists.rego

description: Verify the K8s Namespace exists as evidence.

labels:
  - K8s
  - Namespace

fail-on-missing-evidence: true

evidence:
  signed: false
  content_body_type: generic
  target_type: data
  predicate_type: http://scribesecurity.com/evidence/discovery/v0.1
  labels:
    - "platform=k8s"
    - "asset_type=namespace"
    - >-
      {{- if eq (index .Context "asset-type") "namespace" -}}
      {{- asset_on_target (index .Context "asset-name") -}}
      {{- else -}}
      {{- asset_on_target nil -}}
      {{- end -}}
