config-type: rule
id: k8s-namespace-verify-namespace-termination
name: Verify Namespace Termination
path: verify-namespace-termination.rego

description: Verify Kubernetes namespaces are properly terminated to prevent lingering resources and maintain cluster hygiene.

full-description: |
  This rule verifies that namespaces in Kubernetes are terminated properly within the specified time frame.
  It performs the following steps:
  
  1. Iterates over the namespaces marked for termination in the cluster.
  2. Checks each namespace's termination time against the limit specified in the `with.max_termination_time` configuration.
     - If a namespace's termination time exceeds the limit, the rule flags it as a violation.

  **Evidence Requirements:**
  - Evidence must be provided by the Scribe Platform's CLI tool through scanning Kubernetes resources.

mitigation: >
  Ensures that namespaces are terminated in a timely manner, preventing lingering resources and maintaining cluster hygiene.

inputs:
  - name: namespaces
    description: "A list of namespaces to verify (supports regex)."
    type: array
    required: false

input_example: |
  namespaces:
    - ".*"

labels:
  - K8s
  - Namespace

evidence:
  signed: false
  content_body_type: generic
  target_type: data
  predicate_type: http://scribesecurity.com/evidence/discovery/v0.1
  labels:
    - "asset_type=namespace"
    - "platform=k8s"

with:
  namespaces:
    - ".*"
