config-type: rule
id: k8s-namespace-white-listed-namespaces
name: Allowed Namespaces
path: white-listed-namespaces.rego

description: Verify only namespaces specified in the Allowed List are allowed within the cluster.

labels:
  - K8s
  - Namespace

evidence:
  signed: false
  content_body_type: generic
  target_type: data
  predicate_type: http://scribesecurity.com/evidence/discovery/v0.1
  labels:
    - "asset_type=namespace"
    - "platform=k8s"

with:
  namespaces: []

inputs:
  - name: namespaces
    description: "A list of allowed namespaces."
    type: array
    required: false

full-description: |
  This rule ensures that only namespaces specified in the whitelist are allowed within the Kubernetes cluster.
  It performs the following steps:
  
  1. Iterates over the namespaces in the cluster.
  2. Checks each namespace against the whitelist specified in the `with.namespaces` configuration.
     - If a namespace is not in the whitelist, the rule flags it as a violation.

  **Evidence Requirements:**
  - Evidence must be provided by the Scribe Platform's CLI tool through scanning Kubernetes resources.

notes: |
  **Input**
  `namespaces` is a list of allowed namespaces.

  **Input Example:**
  
  ```yaml
  - uses: k8s/namespace/white-listed-namespaces@v2/rules
    with:
      namespaces:
        - default
        - kube-system
  ```

mitigation: >
  Ensures that only approved namespaces are allowed within the Kubernetes cluster, reducing the risk of unauthorized or misconfigured namespaces.
