name: white-listed-pod
path: white-listed-pod.rego

level: warning

description: "A rule to verify that all pods are allowed"

evidence:
  signed: false
  format-type: generic
  target_type: data
  predicate_type: http://scribesecurity.com/evidence/discovery/v0.1
  labels:
    - "asset_type=namespace"

with:
  // Required 
  white_listed_pod: []

  // Optional
  verify_namespaces: []
