name: white-listed-pod
path: white-listed-pod.rego

level: warning

description: "A rule to verify that all pod are allowed"

evidence:
  signed: false
  content_body_type: generic
  target_type: data
  predicate_type: http://scribesecurity.com/evidence/discovery/v0.1
  labels:
    - "asset_type=namespace"

with:
  white_listed_pod: []
  verify_namespaces:
    - ".*"
