name: Trigger Scribe Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - dev
  create:
    tags:
      - '*'

env:
  PRODUCT_KEY: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' && 'sample-policies-dev' || 'sample-policies-release' }}
  PRODUCT_VERSION: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' && 'dev-release' || github.ref_name }}
  EVENT_TYPE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' && 'sample-policies-prerelease' || 'sample-policies-release' }}


jobs:

# Typically here will come the jobs that build a docker image and push it to DockerHub
  trigger:
    name: Trigger Scribe Workflow
    uses: scribe-public/reusable-workflows/.github/workflows/trigger.yaml@main
    with:
        product: "${{ PRODUCT_KEY }}" 
        version: "${{ PRODUCT_VERSION }}"
        event_type: "${{ EVENT_TYPE }}"
        workflow_github_org: scribe-security
        workflow_github_repo: dogfooding
    secrets: 
        WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}